using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Whiteboard.Common.Geo {
    public class Country {
        public string Code { get; set; }
        public string Name { get; set; }
    }
    public static class Regions {
        private static List<Country> countries;

        static Regions() {
            countries = new List<Country>();
            countries.Add(new Country() { Code = "AF", Name = "Afghanistan" });
            countries.Add(new Country() { Code = "AL", Name = "Albania" });
            countries.Add(new Country() { Code = "DZ", Name = "Algeria" });
            countries.Add(new Country() { Code = "AS", Name = "American Samoa" });
            countries.Add(new Country() { Code = "AD", Name = "Andorra" });
            countries.Add(new Country() { Code = "AG", Name = "Angola" });
            countries.Add(new Country() { Code = "AI", Name = "Anguilla" });
            countries.Add(new Country() { Code = "AG", Name = "Antigua &amp; Barbuda" });
            countries.Add(new Country() { Code = "AR", Name = "Argentina" });
            countries.Add(new Country() { Code = "AA", Name = "Armenia" });
            countries.Add(new Country() { Code = "AW", Name = "Aruba" });
            countries.Add(new Country() { Code = "AU", Name = "Australia" });
            countries.Add(new Country() { Code = "AT", Name = "Austria" });
            countries.Add(new Country() { Code = "AZ", Name = "Azerbaijan" });
            countries.Add(new Country() { Code = "BS", Name = "Bahamas" });
            countries.Add(new Country() { Code = "BH", Name = "Bahrain" });
            countries.Add(new Country() { Code = "BD", Name = "Bangladesh" });
            countries.Add(new Country() { Code = "BB", Name = "Barbados" });
            countries.Add(new Country() { Code = "BY", Name = "Belarus" });
            countries.Add(new Country() { Code = "BE", Name = "Belgium" });
            countries.Add(new Country() { Code = "BZ", Name = "Belize" });
            countries.Add(new Country() { Code = "BJ", Name = "Benin" });
            countries.Add(new Country() { Code = "BM", Name = "Bermuda" });
            countries.Add(new Country() { Code = "BT", Name = "Bhutan" });
            countries.Add(new Country() { Code = "BO", Name = "Bolivia" });
            countries.Add(new Country() { Code = "BL", Name = "Bonaire" });
            countries.Add(new Country() { Code = "BA", Name = "Bosnia &amp; Herzegovina" });
            countries.Add(new Country() { Code = "BW", Name = "Botswana" });
            countries.Add(new Country() { Code = "BR", Name = "Brazil" });
            countries.Add(new Country() { Code = "BC", Name = "British Indian Ocean Ter" });
            countries.Add(new Country() { Code = "BN", Name = "Brunei" });
            countries.Add(new Country() { Code = "BG", Name = "Bulgaria" });
            countries.Add(new Country() { Code = "BF", Name = "Burkina Faso" });
            countries.Add(new Country() { Code = "BI", Name = "Burundi" });
            countries.Add(new Country() { Code = "KH", Name = "Cambodia" });
            countries.Add(new Country() { Code = "CM", Name = "Cameroon" });
            countries.Add(new Country() { Code = "CA", Name = "Canada" });
            countries.Add(new Country() { Code = "IC", Name = "Canary Islands" });
            countries.Add(new Country() { Code = "CV", Name = "Cape Verde" });
            countries.Add(new Country() { Code = "KY", Name = "Cayman Islands" });
            countries.Add(new Country() { Code = "CF", Name = "Central African Republic" });
            countries.Add(new Country() { Code = "TD", Name = "Chad" });
            countries.Add(new Country() { Code = "CD", Name = "Channel Islands" });
            countries.Add(new Country() { Code = "CL", Name = "Chile" });
            countries.Add(new Country() { Code = "CN", Name = "China" });
            countries.Add(new Country() { Code = "CI", Name = "Christmas Island" });
            countries.Add(new Country() { Code = "CS", Name = "Cocos Island" });
            countries.Add(new Country() { Code = "CO", Name = "Colombia" });
            countries.Add(new Country() { Code = "CC", Name = "Comoros" });
            countries.Add(new Country() { Code = "CG", Name = "Congo" });
            countries.Add(new Country() { Code = "CK", Name = "Cook Islands" });
            countries.Add(new Country() { Code = "CR", Name = "Costa Rica" });
            countries.Add(new Country() { Code = "CT", Name = "Cote D'Ivoire" });
            countries.Add(new Country() { Code = "HR", Name = "Croatia" });
            countries.Add(new Country() { Code = "CU", Name = "Cuba" });
            countries.Add(new Country() { Code = "CB", Name = "Curacao" });
            countries.Add(new Country() { Code = "CY", Name = "Cyprus" });
            countries.Add(new Country() { Code = "CZ", Name = "Czech Republic" });
            countries.Add(new Country() { Code = "DK", Name = "Denmark" });
            countries.Add(new Country() { Code = "DJ", Name = "Djibouti" });
            countries.Add(new Country() { Code = "DM", Name = "Dominica" });
            countries.Add(new Country() { Code = "DO", Name = "Dominican Republic" });
            countries.Add(new Country() { Code = "TM", Name = "East Timor" });
            countries.Add(new Country() { Code = "EC", Name = "Ecuador" });
            countries.Add(new Country() { Code = "EG", Name = "Egypt" });
            countries.Add(new Country() { Code = "SV", Name = "El Salvador" });
            countries.Add(new Country() { Code = "GQ", Name = "Equatorial Guinea" });
            countries.Add(new Country() { Code = "ER", Name = "Eritrea" });
            countries.Add(new Country() { Code = "EE", Name = "Estonia" });
            countries.Add(new Country() { Code = "ET", Name = "Ethiopia" });
            countries.Add(new Country() { Code = "FA", Name = "Falkland Islands" });
            countries.Add(new Country() { Code = "FO", Name = "Faroe Islands" });
            countries.Add(new Country() { Code = "FJ", Name = "Fiji" });
            countries.Add(new Country() { Code = "FI", Name = "Finland" });
            countries.Add(new Country() { Code = "FR", Name = "France" });
            countries.Add(new Country() { Code = "GF", Name = "French Guiana" });
            countries.Add(new Country() { Code = "PF", Name = "French Polynesia" });
            countries.Add(new Country() { Code = "FS", Name = "French Southern Ter" });
            countries.Add(new Country() { Code = "GA", Name = "Gabon" });
            countries.Add(new Country() { Code = "GM", Name = "Gambia" });
            countries.Add(new Country() { Code = "GE", Name = "Georgia" });
            countries.Add(new Country() { Code = "DE", Name = "Germany" });
            countries.Add(new Country() { Code = "GH", Name = "Ghana" });
            countries.Add(new Country() { Code = "GI", Name = "Gibraltar" });
            countries.Add(new Country() { Code = "GB", Name = "Great Britain" });
            countries.Add(new Country() { Code = "GR", Name = "Greece" });
            countries.Add(new Country() { Code = "GL", Name = "Greenland" });
            countries.Add(new Country() { Code = "GD", Name = "Grenada" });
            countries.Add(new Country() { Code = "GP", Name = "Guadeloupe" });
            countries.Add(new Country() { Code = "GU", Name = "Guam" });
            countries.Add(new Country() { Code = "GT", Name = "Guatemala" });
            countries.Add(new Country() { Code = "GN", Name = "Guinea" });
            countries.Add(new Country() { Code = "GY", Name = "Guyana" });
            countries.Add(new Country() { Code = "HT", Name = "Haiti" });
            countries.Add(new Country() { Code = "HW", Name = "Hawaii" });
            countries.Add(new Country() { Code = "HN", Name = "Honduras" });
            countries.Add(new Country() { Code = "HK", Name = "Hong Kong" });
            countries.Add(new Country() { Code = "HU", Name = "Hungary" });
            countries.Add(new Country() { Code = "IS", Name = "Iceland" });
            countries.Add(new Country() { Code = "IN", Name = "India" });
            countries.Add(new Country() { Code = "ID", Name = "Indonesia" });
            countries.Add(new Country() { Code = "IA", Name = "Iran" });
            countries.Add(new Country() { Code = "IQ", Name = "Iraq" });
            countries.Add(new Country() { Code = "IR", Name = "Ireland" });
            countries.Add(new Country() { Code = "IM", Name = "Isle of Man" });
            countries.Add(new Country() { Code = "IL", Name = "Israel" });
            countries.Add(new Country() { Code = "IT", Name = "Italy" });
            countries.Add(new Country() { Code = "JM", Name = "Jamaica" });
            countries.Add(new Country() { Code = "JP", Name = "Japan" });
            countries.Add(new Country() { Code = "JO", Name = "Jordan" });
            countries.Add(new Country() { Code = "KZ", Name = "Kazakhstan" });
            countries.Add(new Country() { Code = "KE", Name = "Kenya" });
            countries.Add(new Country() { Code = "KI", Name = "Kiribati" });
            countries.Add(new Country() { Code = "NK", Name = "Korea North" });
            countries.Add(new Country() { Code = "KS", Name = "Korea South" });
            countries.Add(new Country() { Code = "KW", Name = "Kuwait" });
            countries.Add(new Country() { Code = "KG", Name = "Kyrgyzstan" });
            countries.Add(new Country() { Code = "LA", Name = "Laos" });
            countries.Add(new Country() { Code = "LV", Name = "Latvia" });
            countries.Add(new Country() { Code = "LB", Name = "Lebanon" });
            countries.Add(new Country() { Code = "LS", Name = "Lesotho" });
            countries.Add(new Country() { Code = "LR", Name = "Liberia" });
            countries.Add(new Country() { Code = "LY", Name = "Libya" });
            countries.Add(new Country() { Code = "LI", Name = "Liechtenstein" });
            countries.Add(new Country() { Code = "LT", Name = "Lithuania" });
            countries.Add(new Country() { Code = "LU", Name = "Luxembourg" });
            countries.Add(new Country() { Code = "MO", Name = "Macau" });
            countries.Add(new Country() { Code = "MK", Name = "Macedonia" });
            countries.Add(new Country() { Code = "MG", Name = "Madagascar" });
            countries.Add(new Country() { Code = "MY", Name = "Malaysia" });
            countries.Add(new Country() { Code = "MW", Name = "Malawi" });
            countries.Add(new Country() { Code = "MV", Name = "Maldives" });
            countries.Add(new Country() { Code = "ML", Name = "Mali" });
            countries.Add(new Country() { Code = "MT", Name = "Malta" });
            countries.Add(new Country() { Code = "MH", Name = "Marshall Islands" });
            countries.Add(new Country() { Code = "MQ", Name = "Martinique" });
            countries.Add(new Country() { Code = "MR", Name = "Mauritania" });
            countries.Add(new Country() { Code = "MU", Name = "Mauritius" });
            countries.Add(new Country() { Code = "ME", Name = "Mayotte" });
            countries.Add(new Country() { Code = "MX", Name = "Mexico" });
            countries.Add(new Country() { Code = "MI", Name = "Midway Islands" });
            countries.Add(new Country() { Code = "MD", Name = "Moldova" });
            countries.Add(new Country() { Code = "MC", Name = "Monaco" });
            countries.Add(new Country() { Code = "MN", Name = "Mongolia" });
            countries.Add(new Country() { Code = "MS", Name = "Montserrat" });
            countries.Add(new Country() { Code = "MA", Name = "Morocco" });
            countries.Add(new Country() { Code = "MZ", Name = "Mozambique" });
            countries.Add(new Country() { Code = "MM", Name = "Myanmar" });
            countries.Add(new Country() { Code = "NA", Name = "Nambia" });
            countries.Add(new Country() { Code = "NU", Name = "Nauru" });
            countries.Add(new Country() { Code = "NP", Name = "Nepal" });
            countries.Add(new Country() { Code = "AN", Name = "Netherland Antilles" });
            countries.Add(new Country() { Code = "NL", Name = "Netherlands (Holland, Europe)" });
            countries.Add(new Country() { Code = "NV", Name = "Nevis" });
            countries.Add(new Country() { Code = "NC", Name = "New Caledonia" });
            countries.Add(new Country() { Code = "NZ", Name = "New Zealand" });
            countries.Add(new Country() { Code = "NI", Name = "Nicaragua" });
            countries.Add(new Country() { Code = "NE", Name = "Niger" });
            countries.Add(new Country() { Code = "NG", Name = "Nigeria" });
            countries.Add(new Country() { Code = "NW", Name = "Niue" });
            countries.Add(new Country() { Code = "NF", Name = "Norfolk Island" });
            countries.Add(new Country() { Code = "NO", Name = "Norway" });
            countries.Add(new Country() { Code = "OM", Name = "Oman" });
            countries.Add(new Country() { Code = "PK", Name = "Pakistan" });
            countries.Add(new Country() { Code = "PW", Name = "Palau Island" });
            countries.Add(new Country() { Code = "PS", Name = "Palestine" });
            countries.Add(new Country() { Code = "PA", Name = "Panama" });
            countries.Add(new Country() { Code = "PG", Name = "Papua New Guinea" });
            countries.Add(new Country() { Code = "PY", Name = "Paraguay" });
            countries.Add(new Country() { Code = "PE", Name = "Peru" });
            countries.Add(new Country() { Code = "PH", Name = "Philippines" });
            countries.Add(new Country() { Code = "PO", Name = "Pitcairn Island" });
            countries.Add(new Country() { Code = "PL", Name = "Poland" });
            countries.Add(new Country() { Code = "PT", Name = "Portugal" });
            countries.Add(new Country() { Code = "PR", Name = "Puerto Rico" });
            countries.Add(new Country() { Code = "QA", Name = "Qatar" });
            countries.Add(new Country() { Code = "ME", Name = "Republic of Montenegro" });
            countries.Add(new Country() { Code = "RS", Name = "Republic of Serbia" });
            countries.Add(new Country() { Code = "RE", Name = "Reunion" });
            countries.Add(new Country() { Code = "RO", Name = "Romania" });
            countries.Add(new Country() { Code = "RU", Name = "Russia" });
            countries.Add(new Country() { Code = "RW", Name = "Rwanda" });
            countries.Add(new Country() { Code = "NT", Name = "St Barthelemy" });
            countries.Add(new Country() { Code = "EU", Name = "St Eustatius" });
            countries.Add(new Country() { Code = "HE", Name = "St Helena" });
            countries.Add(new Country() { Code = "KN", Name = "St Kitts-Nevis" });
            countries.Add(new Country() { Code = "LC", Name = "St Lucia" });
            countries.Add(new Country() { Code = "MB", Name = "St Maarten" });
            countries.Add(new Country() { Code = "PM", Name = "St Pierre &amp; Miquelon" });
            countries.Add(new Country() { Code = "VC", Name = "St Vincent &amp; Grenadines" });
            countries.Add(new Country() { Code = "SP", Name = "Saipan" });
            countries.Add(new Country() { Code = "SO", Name = "Samoa" });
            countries.Add(new Country() { Code = "AS", Name = "Samoa American" });
            countries.Add(new Country() { Code = "SM", Name = "San Marino" });
            countries.Add(new Country() { Code = "ST", Name = "Sao Tome &amp; Principe" });
            countries.Add(new Country() { Code = "SA", Name = "Saudi Arabia" });
            countries.Add(new Country() { Code = "SN", Name = "Senegal" });
            countries.Add(new Country() { Code = "SC", Name = "Seychelles" });
            countries.Add(new Country() { Code = "SL", Name = "Sierra Leone" });
            countries.Add(new Country() { Code = "SG", Name = "Singapore" });
            countries.Add(new Country() { Code = "SK", Name = "Slovakia" });
            countries.Add(new Country() { Code = "SI", Name = "Slovenia" });
            countries.Add(new Country() { Code = "SB", Name = "Solomon Islands" });
            countries.Add(new Country() { Code = "OI", Name = "Somalia" });
            countries.Add(new Country() { Code = "ZA", Name = "South Africa" });
            countries.Add(new Country() { Code = "ES", Name = "Spain" });
            countries.Add(new Country() { Code = "LK", Name = "Sri Lanka" });
            countries.Add(new Country() { Code = "SD", Name = "Sudan" });
            countries.Add(new Country() { Code = "SR", Name = "Suriname" });
            countries.Add(new Country() { Code = "SZ", Name = "Swaziland" });
            countries.Add(new Country() { Code = "SE", Name = "Sweden" });
            countries.Add(new Country() { Code = "CH", Name = "Switzerland" });
            countries.Add(new Country() { Code = "SY", Name = "Syria" });
            countries.Add(new Country() { Code = "TA", Name = "Tahiti" });
            countries.Add(new Country() { Code = "TW", Name = "Taiwan" });
            countries.Add(new Country() { Code = "TJ", Name = "Tajikistan" });
            countries.Add(new Country() { Code = "TZ", Name = "Tanzania" });
            countries.Add(new Country() { Code = "TH", Name = "Thailand" });
            countries.Add(new Country() { Code = "TG", Name = "Togo" });
            countries.Add(new Country() { Code = "TK", Name = "Tokelau" });
            countries.Add(new Country() { Code = "TO", Name = "Tonga" });
            countries.Add(new Country() { Code = "TT", Name = "Trinidad &amp; Tobago" });
            countries.Add(new Country() { Code = "TN", Name = "Tunisia" });
            countries.Add(new Country() { Code = "TR", Name = "Turkey" });
            countries.Add(new Country() { Code = "TU", Name = "Turkmenistan" });
            countries.Add(new Country() { Code = "TC", Name = "Turks &amp; Caicos Is" });
            countries.Add(new Country() { Code = "TV", Name = "Tuvalu" });
            countries.Add(new Country() { Code = "UG", Name = "Uganda" });
            countries.Add(new Country() { Code = "UA", Name = "Ukraine" });
            countries.Add(new Country() { Code = "AE", Name = "United Arab Emirates" });
            countries.Add(new Country() { Code = "GB", Name = "United Kingdom" });
            countries.Add(new Country() { Code = "US", Name = "United States of America" });
            countries.Add(new Country() { Code = "UY", Name = "Uruguay" });
            countries.Add(new Country() { Code = "UZ", Name = "Uzbekistan" });
            countries.Add(new Country() { Code = "VU", Name = "Vanuatu" });
            countries.Add(new Country() { Code = "VS", Name = "Vatican City State" });
            countries.Add(new Country() { Code = "VE", Name = "Venezuela" });
            countries.Add(new Country() { Code = "VN", Name = "Vietnam" });
            countries.Add(new Country() { Code = "VB", Name = "Virgin Islands (Brit)" });
            countries.Add(new Country() { Code = "VA", Name = "Virgin Islands (USA)" });
            countries.Add(new Country() { Code = "WK", Name = "Wake Island" });
            countries.Add(new Country() { Code = "WF", Name = "Wallis &amp; Futana Is" });
            countries.Add(new Country() { Code = "YE", Name = "Yemen" });
            countries.Add(new Country() { Code = "ZR", Name = "Zaire" });
            countries.Add(new Country() { Code = "ZM", Name = "Zambia" });
            countries.Add(new Country() { Code = "ZW", Name = "Zimbabwe" });
        }

        public static IEnumerable<Country> GetCountries() {
            return countries;
        }
    }
}